### PR TITLE
moved the files into public and src folders

### PR DESCRIPTION
**Pull request by starwarswii**
index.html is now in public, and all the js/css files are in src
no changes were made to any of those files (except package.json)

verify this can still be run on your environment, then merge.

### CODE REVIEW

**Comment by starwarswii** [comment]
looks like whitespace may have been changed? it shouldn't have been...

**Comment by starwarswii** [comment]
not sure what you mean by that

**Comment by bnidevs** [comment]
in index.js, there are imports at the top of the file.

since you moved everything around, can you change the locations for the imports

**Comment by starwarswii** [comment]
plz keep active on mattermost, for faster communication

the imports are relative. i kept the relative paths the same. it works locally for me, no need to change anything. try it out in your environment.

**Pull request merged**
